//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int MABL { get; set; }
        public string NOIDUNGBL { get; set; }
        public Nullable<int> MATHANHVIEN { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
